version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio_s3
    command: ["server", "/data", "--console-address",":9001"]
    environment:
      - MINIO_ROOT_USER=${MINIO_ADMIN:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD:-topsecret}
    ports:
      - '9000:9000'
      - '9001:9001'
    restart: always
